CREATE DATABASE IF NOT EXISTS ContactInformation;

USE ContactInformation;

CREATE TABLE Users (
    ID INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Login VARCHAR(50) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    TeamName VARCHAR(100),
    DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    DateUpdated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE (Login)
);

CREATE TABLE Contacts (
    ID INT NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Phone VARCHAR(20),
    Email VARCHAR(100),
    UserID INT NOT NULL,
    Position VARCHAR(50),
    Side VARCHAR(20),
    DateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
    DateUpdated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY (UserID) REFERENCES Users(ID)
);
